### ISSUE TITLE
load MMapAPI error

### ISSUE THREAD

**Issue by peakcool** [nawawi/eyeOS#1]
Hi, when I installed the start of the project, encountered a mistake, I tried to locate it to solve it, but I did not do, hope to help me solve the next.

The error message is as follows:

> 2017-03-24 03:25:26,868 [DEBUG] bootstrap.Bootstrap: Loading service "FSI.php"...
2017-03-24 03:25:26,868 [DEBUG] fileSystem.FileObjectFactory: FileObjectsFactory initialized successfully
2017-03-24 03:25:26,868 [DEBUG] bootstrap.Bootstrap: Loading service "MMapAPI.php"...
2017-03-24 03:25:26,868 [ERROR] bootstrap.Bootstrap: Cannot load service "MMap"
2017-03-24 03:25:26,868 [DEBUG] bootstrap.Bootstrap: EyeErrorException: Declaration of MMapAPI::getInstance() should be compatible with Kernel::getInstance($class)
	/eyeos/system/kernel/services/MMap/implementations/MMapAPI.php (line 38) 
	/eyeos/system/kernel/services/MMap/implementations/MMapAPI.php (line 38) __lib_exceptions_error_handler(2048, "Declaration of MMapAPI::getInstance() sh"[..], "/Applications/MAMP/htdocs/eyeOS/eyeos/sy"[..], 38, array(1))
	/eyeos/system/bootstrap/Bootstrap.php (line 80) require_once("/Applications/MAMP/htdocs/eyeOS/eyeos/sy"[..])
	/eyeos/system/bootstrap/Bootstrap.php (line 154) load("./system/kernel/services/MMap//implement"[..])
	/eyeos/system/bootstrap/Bootstrap.php (line 175) loadService("MMap")
	/eyeos/system/bootstrap/Bootstrap.php (line 70) loadServices(array(3))

> 2017-03-24 03:25:26,868 [FATAL] root: Uncaught exception detected in the root page! It is likely to come from the bootstrap.
2017-03-24 03:25:26,868 [FATAL] root: EyeBootstrapException: Cannot load service "MMap".
	/eyeos/system/bootstrap/Bootstrap.php (line 163) 
	/eyeos/system/bootstrap/Bootstrap.php (line 175) loadService("MMap")
	/eyeos/system/bootstrap/Bootstrap.php (line 70) loadServices(array(3))

**Comment by peakcool** [comment]
My php environment is 5.6.25, according to the error prompted me in the subclass getInstance function added the default parameters $ class = null, like to `public static function getInstance($class = null) `

**Comment by nawawi** [comment]
hi, this code is too old and not maintained anymore. the error caused by error_reporting set as strict, btw i've fixed it and add some missing files..please update and try again..
